#!/bin/sh
SCRIPT_BASE_DIR=$(dirname $(readlink -f $0))
source $SCRIPT_BASE_DIR/podman.sh
set -e
# for some reasons, even  when the user is in render group, the container still can't access /dev/dri when not started as root
$ROOT_PODMAN run -d --device /dev/kfd --device /dev/dri -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama:rocm || $ROOT_PODMAN start ollama
$PODMAN run -d --network=host -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:11434 --name open-webui --restart always ghcr.io/open-webui/open-webui:main || $PODMAN start open-webui
