FROM rust:latest
ARG UID=1000
ARG GID=1000

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
    sudo \ 
    git \ 
    rsync \ 
    pipx \ 
    redis-server \ 
    clangd \
    # Runtime dependencies, required for .devcontainer
    nmap \
    snmp \
    # netdiag \ not in debian stable anymore?
    pnscan \
    # net-tools is required by some nasl plugins.
    # nasl_pread: Failed to execute child process “netstat” (No such file or directory)
    net-tools 
# Add prepare-user-dirs.sh and execcute it
COPY prepare-user-dirs.sh /prepare-user-dirs.sh
COPY build-cmake-project.sh /usr/local/bin/build-cmake-project.sh
RUN chmod +x /usr/local/bin/build-cmake-project.sh
COPY build-openvas /usr/local/bin/build-openvas
RUN chmod +x /usr/local/bin/build-openvas
COPY build-gvm-libs /usr/local/bin/build-gvm-libs
RUN chmod +x /usr/local/bin/build-gvm-libs
COPY github-clone.sh /usr/local/bin/github-clone
RUN chmod +x /usr/local/bin/github-clone


RUN apt install -y \
        ninja-build \ 
        gettext \ 
        cmake \ 
        unzip \ 
        curl \ 
        build-essential \ 
        nodejs \ 
        ripgrep \ 
        jq \
        golang \
        fzf && \
    github-clone neovim/neovim && \
    cd /workspaces/neovim/neovim && \
    make CMAKE_BUILD_TYPE=RelWithDebInfo && \
    make install
RUN python3 -m pipx install --global greenbone-feed-sync && \
    github-clone greenbone/gvm-libs  && \
    github-clone greenbone/openvas-scanner && \
    github-clone greenbone/openvas-smb && \
    sh /workspaces/greenbone/gvm-libs/.github/install-dependencies.sh && \
    sh /workspaces/greenbone/openvas-smb/.github/install-openvas-smb-dependencies.sh && \
    sh /workspaces/greenbone/openvas-scanner/.github/install-openvas-dependencies.sh && \
    build-gvm-libs && \
    build-openvas && \
    rustup component add rust-analyzer rust-src && \
    bash /prepare-user-dirs.sh && rm /prepare-user-dirs.sh

USER redis
RUN sed 's/redis-openvas/redis/' /workspaces/greenbone/openvas-scanner/config/redis-openvas.conf | tee /etc/redis/redis.conf

USER root
RUN rm -rf /workspaces && apt-get clean && sudo rm -rf /var/lib/apt/lists/*

USER user
